# name: My First CI Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   hello:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 16
#           cache: 'npm'

#       - name: Install dependencies
#         run: npm install

#       - name: Build project
#         run: npm run build


# name: CI with ENV

# on:
#   push:
#     branches:
#       - main

# jobs:
#   test-env:
#     runs-on: ubuntu-latest

#     env:
#       APP_ENV: production
#       APP_NAME: my-app

#     steps:
#       - uses: actions/checkout@v4

#       - name: Print env variables
#         run: |
#           echo "Environment: $APP_ENV"
#           echo "App name: $APP_NAME"


jobs:
  secure-job:
    runs-on: ubuntu-latest

    steps:
      - name: Use secret
        run: echo "Secret is available"
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: echo "DB_PASSWORD"
